#!/bin/bash
#===============================================================================
# Filename: kfdocker-start
# Created on Tue Aug 25 21:55:08 EDT 2020
#
# @author: Kefeng Zhu (zhukefeng@inspur.com, zkf1985@gmail.com, zkf85@163.com)
#
# Start a Docker container with Bash
#===============================================================================
if [ $# != 1 ]; then
    docker ps -a
    echo ""
    echo "== Start a Docker Container =="
    echo "[Usage:] kfdocker_start [container_name]"
    echo ""
    exit
fi
        
CONTAINER=$1
docker start $CONTAINER
docker exec -it $CONTAINER /bin/bash

