#!/bin/bash
#===============================================================================
# Filename: kfip 
# Created on Mon Aug 10 15:12:17 CST 2020
#
# @author: Kefeng Zhu (zhukefeng@inspur.com, zkf1985@gmail.com, zkf85@163.com)
#       Try IPs for the inspur_mini server
#===============================================================================

ROOT=10.159.11.
for (( i=0; i < 255; i=i+1 )); do
     
    ping -c 1 $ROOT$i
    #ping=`ping -c 1 $ROOT$i`

#    if [ $ping -eq 100 ]; then
#        echo ping $ROOT$i fail
#    else
#        echo ping $ROOT$i OK
#    fi

done

