#!/bin/bash
#===============================================================================
# Filename: kftouchsh 
# Created on Thu Mar 13 15:05:12 CST 2019
#
# @author: Kefeng Zhu (zkf1985@gmail.com, zkf85@163.com)
#
# Create a Python scripts with header template.
#
#===============================================================================
#FILE=$1
FILE="solution.py"
echo "\"\"\"
Filename: $FILE 
Created on `date`

@author: Kefeng Zhu (zkf1985@gmail.com, zkf85@163.com)

LeetCode Problem:

\"\"\"

class Solution1:


#===============================================================================
# Test
#===============================================================================
test = {

}

sol = Solution1()
for k, v in test.items():
    res = sol.

    print('-'*80)
    print('Input:', k)
    print('Correct:', v)
    print('Output:', res)
    if res == v: print('Passed.')
    else: print('Wrong!!')

" > $FILE
